core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    HomeHeaderView,
    AboutHeaderView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    createProduct,
    accessories_category,
    baseball_caps_category,
    jackets_category,
    caps_category,
    sneakers_category,
    pajamas_category,
    sandals_category,
    shirts_category,
    tracksuits_category,
    t_shirts_and_tops_category,
    hoodies_and_sweatshirts_category,
    boots_category,
    pants_and_jeans_category,
    shorts_category,
    socks_category,
    search,
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('/', HomeHeaderView.as_view(), name='home'),
    path('about/', AboutHeaderView.as_view(), name='about'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('create_product.html/', createProduct, name='create-product'),
    path('accessories_category/', accessories_category, name='accessories_category'),
    path('baseball_caps_category/', baseball_caps_category, name='baseball_caps_category'),
    path('jackets_category/', jackets_category, name='jackets_category'),
    path('caps_category/', caps_category, name='caps_category'),
    path('sneakers_category/', sneakers_category, name='sneakers_category'),
    path('pajamas_category/', pajamas_category, name='pajamas_category'),
    path('sandals_category/', sandals_category, name='sandals_category'),
    path('shirts_category/', shirts_category, name='shirts_category'),
    path('tracksuits_category/', tracksuits_category, name='tracksuits_category'),
    path('t-shirts_and_tops_category/', t_shirts_and_tops_category, name='t-shirts_and_tops_category'),
    path('hoodies_and_sweatshirts_category/', hoodies_and_sweatshirts_category, name='hoodies_and_sweatshirts_category'),
    path('boots_category/', boots_category, name='boots_category'),
    path('pants_and_jeans_category/', pants_and_jeans_category, name='pants_and_jeans_category'),
    path('shorts_category/', shorts_category, name='shorts_category'),
    path('socks_category/', socks_category, name='socks_category'),
    path('search/', search, name='search'),
]

core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField


# Категорії
CATEGORY_CHOICES = (
    ('AC', 'Аксесуари'), # accessories_category
    ('BC', 'Бейсболки'), # baseball_caps_category
    ('JK', 'Куртки'), # jackets_category
    ('CP', 'Кепки'), # caps_category
    ('SN', 'Кросівки'), # sneakers_category
    ('PM', 'Піжами'), # pajamas_category
    ('SA', 'Сандалі'), # sandals_category
    ('SR', 'Сорочки'), # shirts_category
    ('SW', 'Спортивні костюми'), # tracksuits_category
    ('TT', 'Футболки та топи'), # t-shirts_and_tops_category
    ('HS', 'Худі та толстовки'), # hoodies_and_sweatshirts_category
    ('BT', 'Чоботи'), # boots_category
    ('PJ', 'Штани та джинси'), # pants_and_jeans_category
    ('SH', 'Шорти'), # shorts_category
    ('SC', 'Шкарпетки'), # socks_category
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField("Назва продукту", max_length=100)
    price = models.FloatField("Ціна")
    discount_price = models.FloatField("Ціна зі знижкою", blank=True, null=True)
    category = models.CharField("Категорія", choices=CATEGORY_CHOICES, max_length=2)
    slug = models.SlugField("URL")
    description = models.TextField("Опис")
    image = models.ImageField("Зображення")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)

post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/categories/accessories_category.html
{% extends "categories/base.html" %}
<title>{% block head_title %}Redleem - Категорія Аксесуари{% endblock %}</title>

templates/categories/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    .card {
      height: 100%;
    }

  </style>
</head>

<navbar class="navbar">
    {% include "navbar.html" %}
</navbar>

<body>
<main class="main">
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5" id="nav">
        <div class="dropdown" id="category-button">
          <a class="dropdown-toggle navbar-brand" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Категорії
          </a>
          <div class="dropdown-menu category-menu" id="category-menu">
            <div class="scrollable-menu">
              <ul>
                <li><a class="dropdown-item" href="{% url 'core:accessories_category' %}">Аксесуари</a></li>
                <li><a class="dropdown-item" href="{% url 'core:baseball_caps_category' %}">Бейсболки</a></li>
                <li><a class="dropdown-item" href="{% url 'core:jackets_category' %}">Куртки</a></li>
                <li><a class="dropdown-item" href="{% url 'core:caps_category' %}">Кепки</a></li>
                <li><a class="dropdown-item" href="{% url 'core:sneakers_category' %}">Кросівки</a></li>
                <li><a class="dropdown-item" href="{% url 'core:pajamas_category' %}">Піжами</a></li>
                <li><a class="dropdown-item" href="{% url 'core:sandals_category' %}">Сандалі</a></li>
                <li><a class="dropdown-item" href="{% url 'core:shirts_category' %}">Сорочки</a></li>
                <li><a class="dropdown-item" href="{% url 'core:tracksuits_category' %}">Спортивні костюми</a></li>
                <li><a class="dropdown-item" href="{% url 'core:t-shirts_and_tops_category' %}">Футболки та топи</a></li>
                <li><a class="dropdown-item" href="{% url 'core:hoodies_and_sweatshirts_category' %}">Худі та толстовки</a></li>
                <li><a class="dropdown-item" href="{% url 'core:boots_category' %}">Чоботи</a></li>
                <li><a class="dropdown-item" href="{% url 'core:pants_and_jeans_category' %}">Штани та джинси</a></li>
                <li><a class="dropdown-item" href="{% url 'core:shorts_category' %}">Шорти</a></li>
                <li><a class="dropdown-item" href="{% url 'core:socks_category' %}">Шкарпетки</a></li>
              </ul>
            </div>
          </div>
        </div>

        <div class="d-flex">
          <div class="collapse navbar-collapse" id="basicExampleNav">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="/" style="margin-left: 20px;">Головна
                  <span class="sr-only">(поточний)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'core:about' %}" style="margin-left: 20px;">Про нас</a>
              </li>
            </ul>
            </div>
          </div>

        <div class="ml-auto">
        <div class="d-flex flex-row-reverse">
          <div class="p-2">
            <form class="form-inline" method="get" action="{% url 'core:search' %}">
              <div class="md-form my-0">
                <input class="form-control mr-sm-2" type="text" style="width: 220px;" placeholder="Пошук" aria-label="Search" name="query">
              </div>
            </form>
          </div>
          <div class="p-2">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
              aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          </div>
        </div>
        </div>

      </nav>

      <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

<div class="content">
    {% block content %}
  <section class="text-center mb-4">
    {% if object_list %}
      <div class="row wow fadeIn">
        {% for item in object_list %}
        <div class="col-lg-3 col-md-6 mb-4">
          <div class="card">
            <div class="view overlay">
              <img src="{{ item.image.url }}" class="card-img-top">
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>
            <div class="card-body text-center">
              <a href="" class="grey-text">
                <h5>
                  <a href="" class="grey-text">
                    <h5><span class="badge purple mr-1; badge-pill">{{ item.get_category_display }}</span></h5>
                  </a>
                </h5>
              </a>
              <h5>
                <strong>
                  <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}</a>
                </strong>
              </h5>
              <div class="price-size">
                <p></p>
                <strong>
                  {% if item.discount_price %}
                    <div class="d-inline-flex">
                      <h5 class="mb-0 mr-2"><del class="font-weight-bold red-text">₴ {{ item.price }}</del></h5>
                      <h4 class="mb-0"><span class="font-weight-bold blue-text">₴ {{ item.discount_price }}</span></h4>
                    </div>
                  {% else %}
                    {{ item.price }}
                  {% endif %}
                </strong>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    {% else %}
    <p style="margin-bottom: -15px;"><h5>Немає товарів із цією категорією</h5></p>
    {% endif %}
  </section>
    {% endblock content %}
</div>

    </div>
  </main>

    {% block extra_body %}
    {% endblock %}

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

<div class="footer">

    {% block footer %}

    <footer class="page-footer text-center font-small mt-4 wow fadeIn" id="footer">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>

    <div class="footer-copyright py-3">
      © 2023 Copyright:
      <a href="" target="_blank"> Redleem.com </a>
    </div>

    </footer>

</div>

    {% endblock footer %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

<style>
  .category-menu {
    display: none;
    position: absolute;
    background-color: #fff;
    border: 1px solid #ccc;
    z-index: 1;
    max-height: 200px;
    overflow-y: auto;
  }

  .category-menu.show {
    display: block;
  }

  .category-menu ul {
    list-style-type: none;
    padding: 0;
    margin: 0;
  }

  .category-menu ul li {
    padding: 10px;
  }

  .category-menu ul li:hover {
    background-color: #f0f0f0;
  }

  .navbar {
    margin-right: 0px;
  }

  .main {
    margin-top: 72px;
  }

  .footer {
    margin-right: 0px;
  }

  .content {
    margin-left: 0px;
  }

  #nav {
    margin-bottom: -24px !important;
    background-color: red !important;
  }

  #footer {
    background-color: red !important;
  }
</style>

<script>
    document.addEventListener("DOMContentLoaded", function () {
      const categoryButton = document.getElementById("category-button");
      const categoryMenu = document.getElementById("category-menu");

      categoryButton.addEventListener("mouseover", function () {
        categoryMenu.classList.add("show");
      });

      categoryMenu.addEventListener("mouseout", function () {
        categoryMenu.classList.remove("show");
      });
    });

      document.addEventListener("DOMContentLoaded", function () {
      const categoryButton = document.getElementById("category-button");
      const categoryMenu = document.getElementById("category-menu");

      categoryButton.addEventListener("mouseover", function () {
        categoryMenu.classList.add("show");
      });

      categoryMenu.addEventListener("mouseout", function () {
        categoryMenu.classList.remove("show");
      });

      categoryMenu.addEventListener("click", function (event) {
        if (event.target.tagName === "A") {
          const selectedCategory = event.target.innerText;
        }
      });
    });
</script>

templates/categories/baseball_caps_category.html
{% extends "categories/base.html" %}
<title>{% block head_title %}Redleem - Категорія Бейсболки{% endblock %}</title>

templates/categories/boots_category.html
{% extends "categories/base.html" %}
<title>{% block head_title %}Redleem - Категорія Чоботи{% endblock %}</title>

templates/categories/caps_category.html
{% extends "categories/base.html" %}
<title>{% block head_title %}Redleem - Категорія Кепки{% endblock %}</title>

templates/categories/hoodies_and_sweatshirts_category.html
{% extends "categories/base.html" %}
<title>{% block head_title %}Redleem - Категорія Худі та толстовки{% endblock %}</title>

templates/categories/jackets_category.html
{% extends "categories/base.html" %}
<title>{% block head_title %}Redleem - Категорія Куртки{% endblock %}</title>

templates/categories/pajamas_category.html
{% extends "categories/base.html" %}
<title>{% block head_title %}Redleem - Категорія Піжами{% endblock %}</title>

templates/categories/pants_and_jeans_category.html
{% extends "categories/base.html" %}
<title>{% block head_title %}Redleem - Категорія Штани та джинси{% endblock %}</title>

templates/categories/sandals_category.html
{% extends "categories/base.html" %}
<title>{% block head_title %}Redleem - Категорія Сандалі{% endblock %}</title>

templates/categories/shirts_category.html
{% extends "categories/base.html" %}
<title>{% block head_title %}Redleem - Категорія Сорочки{% endblock %}</title>

templates/categories/shorts_category.html
{% extends "categories/base.html" %}
<title>{% block head_title %}Redleem - Категорія Шорти{% endblock %}</title>

templates/categories/t-shirts_and_tops_category.html
{% extends "categories/base.html" %}
<title>{% block head_title %}Redleem - Категорія Футболки та топи{% endblock %}</title>

templates/categories/tracksuits_category.html
{% extends "categories/base.html" %}
<title>{% block head_title %}Redleem - Категорія Спортивні костюми{% endblock %}</title>